### ISSUE TITLE
Token updates doesn't work

### ISSUE THREAD

**Issue by itemsCenter** [ZykeNetwork/ZykePanel#1]
Hi.

I tried running it on my website and it seems to not to work for some reason. Every time I type in the token it doesn't load anything.

Link to [my site](https://dashboard.samuelmikula.com/discord/).

**Comment by 4yx** [comment]
I just tried it on your site with one of my bots' tokens and it worked.

Have you tried refreshing the token (the refresh token button)? Did you copy the token directly from the Developers section?
Also, can you provide a screenshot with what you see after entering the token?

**Comment by itemsCenter** [comment]
I tried it in Incognito mode and it worked, just realised that the cache might be the issue. I'm dumb, sorry... Thank you anyway.

**Comment by 4yx** [comment]
Glad you got it resolved :)
